services:
  db:
    container_name: lakarte_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lakarte_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - lakarte_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lakarte_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - lakarte_network

  react:
    image: node:18-alpine
    container_name: lakarte_react
    restart: always
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - lakarte_network

volumes:
  db_data:
networks:
  lakarte_network:
